safer initializing of starship prompt

diff --git a/private_dot_config/zsh/dot_zshrc.tmpl b/private_dot_config/zsh/dot_zshrc.tmpl
--- a/private_dot_config/zsh/dot_zshrc.tmpl
+++ b/private_dot_config/zsh/dot_zshrc.tmpl
@@ -173,8 +173,12 @@ ZSH_AUTOSUGGEST_STRATEGY=(history completion)
 
 # ▼ Starship prompt
 
-export STARSHIP_CONFIG=${XDG_CONFIG_HOME}/starship/starship.toml
 
-eval "$(starship init zsh)"
+if (( $+commands[starship] )); then
+  export STARSHIP_CONFIG=${XDG_CONFIG_HOME}/starship/starship.toml
+  eval "$(starship init zsh)"
+else
+  echo 'could not initialize starship prompt: starship was not found. Please install starship first. See: https://starship.rs/guide/#%F0%9F%9A%80-installation' >&2
+fi
 
 # ▲
